// <auto-generated />
namespace BookStoreApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class editmaxlength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editmaxlength));
        
        string IMigrationMetadata.Id
        {
            get { return "202606091313589_edit-maxlength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
